name: Publish npm

on:
  release:
    types: [published]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: latest

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: pnpm

      # - name: Authenticate with the NPM registry
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      #   run: npm config set '//registry.npmjs.org/:_authToken' $NODE_AUTH_TOKEN

      - name: publish
        run: |
          git config --global user.name
          git config --global user.email "yqcyecong@163.com"
          git config --global user.name "_Ghosteye"
          git config --global user.name
          npm version ${{ github.event.release.tag_name }} --no-git-tag-version --force
          pnpm install --frozen-lockfile
          pnpm run build
          cd lib
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

